var edges = [
{from: "Intel/dpt-hybrid-midas", to: "Intel", title: "organisation", color: "#DE5947"},
{from: "Intel/dpt-hybrid-midas", to: "depth-estimation", title: "Main Task", color: "#8EDE47"},
{from: "Intel/dpt-hybrid-midas", to: "apache-2.0", title: "License", color: "#000000"},
{from: "Intel/dpt-hybrid-midas", to: "semantic-segmentation-on-ade20k", title: "Benchmark", color: "#c1e769"},
{from: "semantic-segmentation-on-ade20k", to: "Validation mIoU", title: "Metric", color: "#9c8acb"},
{from: "Validation mIoU", to: "49.02", title: "Score", color: "#d0cae1"},
{from: "Intel/dpt-hybrid-midas", to: "semantic-segmentation-on-ade20k-val", title: "Benchmark", color: "#c1e769"},
{from: "semantic-segmentation-on-ade20k-val", to: "mIoU", title: "Metric", color: "#9c8acb"},
{from: "mIoU", to: "49.02", title: "Score", color: "#d0cae1"},
{from: "semantic-segmentation-on-ade20k-val", to: "Pixel Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Pixel Accuracy", to: "83.11", title: "Score", color: "#d0cae1"},
{from: "Intel/dpt-hybrid-midas", to: "monocular-depth-estimation-on-kitti-eigen", title: "Benchmark", color: "#c1e769"},
{from: "monocular-depth-estimation-on-kitti-eigen", to: "absolute relative error", title: "Metric", color: "#9c8acb"},
{from: "absolute relative error", to: "0.062", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-kitti-eigen", to: "RMSE", title: "Metric", color: "#9c8acb"},
{from: "RMSE", to: "2.573", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-kitti-eigen", to: "RMSE log", title: "Metric", color: "#9c8acb"},
{from: "RMSE log", to: "0.092", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-kitti-eigen", to: "Delta < 1.25", title: "Metric", color: "#9c8acb"},
{from: "Delta < 1.25", to: "0.959", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-kitti-eigen", to: "Delta < 1.25^2", title: "Metric", color: "#9c8acb"},
{from: "Delta < 1.25^2", to: "0.995", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-kitti-eigen", to: "Delta < 1.25^3", title: "Metric", color: "#9c8acb"},
{from: "Delta < 1.25^3", to: "0.999", title: "Score", color: "#d0cae1"},
{from: "Intel/dpt-hybrid-midas", to: "monocular-depth-estimation-on-nyu-depth-v2", title: "Benchmark", color: "#c1e769"},
{from: "monocular-depth-estimation-on-nyu-depth-v2", to: "RMSE", title: "Metric", color: "#9c8acb"},
{from: "RMSE", to: "0.357", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-nyu-depth-v2", to: "absolute relative error", title: "Metric", color: "#9c8acb"},
{from: "absolute relative error", to: "0.110", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-nyu-depth-v2", to: "Delta < 1.25", title: "Metric", color: "#9c8acb"},
{from: "Delta < 1.25", to: "0.904", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-nyu-depth-v2", to: "Delta < 1.25^2", title: "Metric", color: "#9c8acb"},
{from: "Delta < 1.25^2", to: "0.988", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-nyu-depth-v2", to: "Delta < 1.25^3", title: "Metric", color: "#9c8acb"},
{from: "Delta < 1.25^3", to: "0.994", title: "Score", color: "#d0cae1"},
{from: "monocular-depth-estimation-on-nyu-depth-v2", to: "log 10", title: "Metric", color: "#9c8acb"},
{from: "log 10", to: "0.045", title: "Score", color: "#d0cae1"},
{from: "Intel/dpt-hybrid-midas", to: "semantic-segmentation-on-pascal-context", title: "Benchmark", color: "#c1e769"},
{from: "semantic-segmentation-on-pascal-context", to: "mIoU", title: "Metric", color: "#9c8acb"},
{from: "mIoU", to: "60.46", title: "Score", color: "#d0cae1"},
{from: "Intel/dpt-hybrid-midas", to: "estimate_depth", title: "Python Code", color: "#348b40"},
{from: "Salesforce/blip-image-captioning-base", to: "Salesforce", title: "organisation", color: "#DE5947"},
{from: "Salesforce/blip-image-captioning-base", to: "image-to-text", title: "Main Task", color: "#8EDE47"},
{from: "Salesforce/blip-image-captioning-base", to: "bsd-3-clause", title: "License", color: "#000000"},
{from: "Salesforce/blip-image-captioning-base", to: "image-text-matching-on-commercialadsdataset", title: "Benchmark", color: "#c1e769"},
{from: "image-text-matching-on-commercialadsdataset", to: "ADD(S) AUC", title: "Metric", color: "#9c8acb"},
{from: "ADD(S) AUC", to: "83.51", title: "Score", color: "#d0cae1"},
{from: "Salesforce/blip-image-captioning-base", to: "open-vocabulary-attribute-detection-on-ovad-1", title: "Benchmark", color: "#c1e769"},
{from: "open-vocabulary-attribute-detection-on-ovad-1", to: "mean average precision", title: "Metric", color: "#9c8acb"},
{from: "mean average precision", to: "24.3", title: "Score", color: "#d0cae1"},
{from: "Salesforce/blip-image-captioning-base", to: "caption_image", title: "Python Code", color: "#348b40"},
{from: "Salesforce/blip-vqa-base", to: "Salesforce", title: "organisation", color: "#DE5947"},
{from: "Salesforce/blip-vqa-base", to: "visual-question-answering", title: "Main Task", color: "#8EDE47"},
{from: "Salesforce/blip-vqa-base", to: "bsd-3-clause", title: "License", color: "#000000"},
{from: "Salesforce/blip-vqa-base", to: "image-text-matching-on-commercialadsdataset", title: "Benchmark", color: "#c1e769"},
{from: "image-text-matching-on-commercialadsdataset", to: "ADD(S) AUC", title: "Metric", color: "#9c8acb"},
{from: "ADD(S) AUC", to: "83.51", title: "Score", color: "#d0cae1"},
{from: "Salesforce/blip-vqa-base", to: "open-vocabulary-attribute-detection-on-ovad-1", title: "Benchmark", color: "#c1e769"},
{from: "open-vocabulary-attribute-detection-on-ovad-1", to: "mean average precision", title: "Metric", color: "#9c8acb"},
{from: "mean average precision", to: "24.3", title: "Score", color: "#d0cae1"},
{from: "Salesforce/blip-vqa-base", to: "answer_question_based_on_image", title: "Python Code", color: "#348b40"},
{from: "Yale-LILY/reastap-large", to: "Yale-LILY", title: "organisation", color: "#DE5947"},
{from: "Yale-LILY/reastap-large", to: "text2text-generation", title: "Main Task", color: "#8EDE47"},
{from: "Yale-LILY/reastap-large", to: "table-based-fact-verification-on-tabfact", title: "Benchmark", color: "#c1e769"},
{from: "table-based-fact-verification-on-tabfact", to: "Test", title: "Metric", color: "#9c8acb"},
{from: "Test", to: "84.9", title: "Score", color: "#d0cae1"},
{from: "table-based-fact-verification-on-tabfact", to: "Val", title: "Metric", color: "#9c8acb"},
{from: "Val", to: "84.6", title: "Score", color: "#d0cae1"},
{from: "Yale-LILY/reastap-large", to: "semantic-parsing-on-wikisql-1", title: "Benchmark", color: "#c1e769"},
{from: "semantic-parsing-on-wikisql-1", to: "Denotation accuracy (test)", title: "Metric", color: "#9c8acb"},
{from: "Denotation accuracy (test)", to: "89.2", title: "Score", color: "#d0cae1"},
{from: "Yale-LILY/reastap-large", to: "semantic-parsing-on-wikitablequestions", title: "Benchmark", color: "#c1e769"},
{from: "semantic-parsing-on-wikitablequestions", to: "Accuracy (Dev)", title: "Metric", color: "#9c8acb"},
{from: "Accuracy (Dev)", to: "59.7", title: "Score", color: "#d0cae1"},
{from: "semantic-parsing-on-wikitablequestions", to: "Accuracy (Test)", title: "Metric", color: "#9c8acb"},
{from: "Accuracy (Test)", to: "58.7", title: "Score", color: "#d0cae1"},
{from: "Yale-LILY/reastap-large", to: "query_table", title: "Python Code", color: "#348b40"},
{from: "Yale-LILY/reastap-large", to: "en", title: "language", color: "#9ac7e3"},
{from: "distilbert/distilbert-base-uncased-distilled-squad", to: "distilbert", title: "organisation", color: "#DE5947"},
{from: "distilbert/distilbert-base-uncased-distilled-squad", to: "question-answering", title: "Main Task", color: "#8EDE47"},
{from: "distilbert/distilbert-base-uncased-distilled-squad", to: "apache-2.0", title: "License", color: "#000000"},
{from: "distilbert/distilbert-base-uncased-distilled-squad", to: "question-answering-on-squad11-dev", title: "Benchmark", color: "#c1e769"},
{from: "question-answering-on-squad11-dev", to: "EM", title: "Metric", color: "#9c8acb"},
{from: "EM", to: "77.7", title: "Score", color: "#d0cae1"},
{from: "distilbert/distilbert-base-uncased-distilled-squad", to: "question_answering", title: "Python Code", color: "#348b40"},
{from: "distilbert/distilbert-base-uncased-distilled-squad", to: "en", title: "language", color: "#9ac7e3"},
{from: "dslim/bert-base-NER", to: "dslim", title: "organisation", color: "#DE5947"},
{from: "dslim/bert-base-NER", to: "token-classification", title: "Main Task", color: "#8EDE47"},
{from: "dslim/bert-base-NER", to: "mit", title: "License", color: "#000000"},
{from: "dslim/bert-base-NER", to: "question-answering-on-coqa", title: "Benchmark", color: "#c1e769"},
{from: "question-answering-on-coqa", to: "In-domain", title: "Metric", color: "#9c8acb"},
{from: "In-domain", to: "79.8", title: "Score", color: "#d0cae1"},
{from: "question-answering-on-coqa", to: "Out-of-domain", title: "Metric", color: "#9c8acb"},
{from: "Out-of-domain", to: "74.1", title: "Score", color: "#d0cae1"},
{from: "question-answering-on-coqa", to: "Overall", title: "Metric", color: "#9c8acb"},
{from: "Overall", to: "78.1", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "type-prediction-on-manytypes4typescript", title: "Benchmark", color: "#c1e769"},
{from: "type-prediction-on-manytypes4typescript", to: "Average Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Average Accuracy", to: "57.52", title: "Score", color: "#d0cae1"},
{from: "type-prediction-on-manytypes4typescript", to: "Average Precision", title: "Metric", color: "#9c8acb"},
{from: "Average Precision", to: "54.18", title: "Score", color: "#d0cae1"},
{from: "type-prediction-on-manytypes4typescript", to: "Average Recall", title: "Metric", color: "#9c8acb"},
{from: "Average Recall", to: "54.02", title: "Score", color: "#d0cae1"},
{from: "type-prediction-on-manytypes4typescript", to: "Average F1", title: "Metric", color: "#9c8acb"},
{from: "Average F1", to: "54.10", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "named-entity-recognition-on-ncbi-disease-1", title: "Benchmark", color: "#c1e769"},
{from: "named-entity-recognition-on-ncbi-disease-1", to: "F1", title: "Metric", color: "#9c8acb"},
{from: "F1", to: "86.37", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "multimodal-intent-recognition-on-photochat", title: "Benchmark", color: "#c1e769"},
{from: "multimodal-intent-recognition-on-photochat", to: "F1", title: "Metric", color: "#9c8acb"},
{from: "F1", to: "53.2", title: "Score", color: "#d0cae1"},
{from: "multimodal-intent-recognition-on-photochat", to: "Precision", title: "Metric", color: "#9c8acb"},
{from: "Precision", to: "56.1", title: "Score", color: "#d0cae1"},
{from: "multimodal-intent-recognition-on-photochat", to: "Recall", title: "Metric", color: "#9c8acb"},
{from: "Recall", to: "50.6", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "common-sense-reasoning-on-record", title: "Benchmark", color: "#c1e769"},
{from: "common-sense-reasoning-on-record", to: "F1", title: "Metric", color: "#9c8acb"},
{from: "F1", to: "56.065", title: "Score", color: "#d0cae1"},
{from: "common-sense-reasoning-on-record", to: "EM", title: "Metric", color: "#9c8acb"},
{from: "EM", to: "54.040", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "named-entity-recognition-on-scierc", title: "Benchmark", color: "#c1e769"},
{from: "named-entity-recognition-on-scierc", to: "F1", title: "Metric", color: "#9c8acb"},
{from: "F1", to: "65.24", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "linear-probe-classification-on-senteval", title: "Benchmark", color: "#c1e769"},
{from: "linear-probe-classification-on-senteval", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "84.9", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "cross-lingual-natural-language-inference-on-3", title: "Benchmark", color: "#c1e769"},
{from: "cross-lingual-natural-language-inference-on-3", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "70.5%", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "cross-lingual-natural-language-inference-on-1", title: "Benchmark", color: "#c1e769"},
{from: "cross-lingual-natural-language-inference-on-1", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "74.3%", title: "Score", color: "#d0cae1"},
{from: "dslim/bert-base-NER", to: "named_entity_recognition", title: "Python Code", color: "#348b40"},
{from: "dslim/bert-base-NER", to: "en", title: "language", color: "#9ac7e3"},
{from: "facebook/bart-large-cnn", to: "facebook", title: "organisation", color: "#DE5947"},
{from: "facebook/bart-large-cnn", to: "summarization", title: "Main Task", color: "#8EDE47"},
{from: "facebook/bart-large-cnn", to: "mit", title: "License", color: "#000000"},
{from: "facebook/bart-large-cnn", to: "abstractive-text-summarization-on-cnn-daily", title: "Benchmark", color: "#c1e769"},
{from: "abstractive-text-summarization-on-cnn-daily", to: "ROUGE-1", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-1", to: "44.16", title: "Score", color: "#d0cae1"},
{from: "abstractive-text-summarization-on-cnn-daily", to: "ROUGE-2", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-2", to: "21.28", title: "Score", color: "#d0cae1"},
{from: "abstractive-text-summarization-on-cnn-daily", to: "ROUGE-L", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-L", to: "40.90", title: "Score", color: "#d0cae1"},
{from: "facebook/bart-large-cnn", to: "open-domain-question-answering-on-eli5", title: "Benchmark", color: "#c1e769"},
{from: "open-domain-question-answering-on-eli5", to: "Rouge-L", title: "Metric", color: "#9c8acb"},
{from: "Rouge-L", to: "24.3", title: "Score", color: "#d0cae1"},
{from: "open-domain-question-answering-on-eli5", to: "Rouge-1", title: "Metric", color: "#9c8acb"},
{from: "Rouge-1", to: "30.6", title: "Score", color: "#d0cae1"},
{from: "open-domain-question-answering-on-eli5", to: "Rouge-2", title: "Metric", color: "#9c8acb"},
{from: "Rouge-2", to: "6.2", title: "Score", color: "#d0cae1"},
{from: "facebook/bart-large-cnn", to: "text-summarization-on-x-sum", title: "Benchmark", color: "#c1e769"},
{from: "text-summarization-on-x-sum", to: "ROUGE-1", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-1", to: "45.14", title: "Score", color: "#d0cae1"},
{from: "text-summarization-on-x-sum", to: "ROUGE-2", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-2", to: "22.27", title: "Score", color: "#d0cae1"},
{from: "text-summarization-on-x-sum", to: "ROUGE-3", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-3", to: "37.25", title: "Score", color: "#d0cae1"},
{from: "facebook/bart-large-cnn", to: "summarize_text", title: "Python Code", color: "#348b40"},
{from: "facebook/bart-large-cnn", to: "en", title: "language", color: "#9ac7e3"},
{from: "facebook/bart-large-mnli", to: "facebook", title: "organisation", color: "#DE5947"},
{from: "facebook/bart-large-mnli", to: "zero-shot-classification", title: "Main Task", color: "#8EDE47"},
{from: "facebook/bart-large-mnli", to: "mit", title: "License", color: "#000000"},
{from: "facebook/bart-large-mnli", to: "abstractive-text-summarization-on-cnn-daily", title: "Benchmark", color: "#c1e769"},
{from: "abstractive-text-summarization-on-cnn-daily", to: "ROUGE-1", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-1", to: "44.16", title: "Score", color: "#d0cae1"},
{from: "abstractive-text-summarization-on-cnn-daily", to: "ROUGE-2", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-2", to: "21.28", title: "Score", color: "#d0cae1"},
{from: "abstractive-text-summarization-on-cnn-daily", to: "ROUGE-L", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-L", to: "40.90", title: "Score", color: "#d0cae1"},
{from: "facebook/bart-large-mnli", to: "open-domain-question-answering-on-eli5", title: "Benchmark", color: "#c1e769"},
{from: "open-domain-question-answering-on-eli5", to: "Rouge-L", title: "Metric", color: "#9c8acb"},
{from: "Rouge-L", to: "24.3", title: "Score", color: "#d0cae1"},
{from: "open-domain-question-answering-on-eli5", to: "Rouge-1", title: "Metric", color: "#9c8acb"},
{from: "Rouge-1", to: "30.6", title: "Score", color: "#d0cae1"},
{from: "open-domain-question-answering-on-eli5", to: "Rouge-2", title: "Metric", color: "#9c8acb"},
{from: "Rouge-2", to: "6.2", title: "Score", color: "#d0cae1"},
{from: "facebook/bart-large-mnli", to: "text-summarization-on-x-sum", title: "Benchmark", color: "#c1e769"},
{from: "text-summarization-on-x-sum", to: "ROUGE-1", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-1", to: "45.14", title: "Score", color: "#d0cae1"},
{from: "text-summarization-on-x-sum", to: "ROUGE-2", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-2", to: "22.27", title: "Score", color: "#d0cae1"},
{from: "text-summarization-on-x-sum", to: "ROUGE-3", title: "Metric", color: "#9c8acb"},
{from: "ROUGE-3", to: "37.25", title: "Score", color: "#d0cae1"},
{from: "facebook/bart-large-mnli", to: "text_classification_using_bart", title: "Python Code", color: "#348b40"},
{from: "facebook/detr-resnet-101", to: "facebook", title: "organisation", color: "#DE5947"},
{from: "facebook/detr-resnet-101", to: "object-detection", title: "Main Task", color: "#8EDE47"},
{from: "facebook/detr-resnet-101", to: "apache-2.0", title: "License", color: "#000000"},
{from: "facebook/detr-resnet-101", to: "panoptic-segmentation-on-coco-minival", title: "Benchmark", color: "#c1e769"},
{from: "panoptic-segmentation-on-coco-minival", to: "PQ", title: "Metric", color: "#9c8acb"},
{from: "PQ", to: "45.1", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "SQ", title: "Metric", color: "#9c8acb"},
{from: "SQ", to: "79.9", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "RQ", title: "Metric", color: "#9c8acb"},
{from: "RQ", to: "55.5", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "PQth", title: "Metric", color: "#9c8acb"},
{from: "PQth", to: "50.5", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "SQth", title: "Metric", color: "#9c8acb"},
{from: "SQth", to: "80.9", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "RQth", title: "Metric", color: "#9c8acb"},
{from: "RQth", to: "61.7", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "PQst", title: "Metric", color: "#9c8acb"},
{from: "PQst", to: "37", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "SQst", title: "Metric", color: "#9c8acb"},
{from: "SQst", to: "78.5", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "RQst", title: "Metric", color: "#9c8acb"},
{from: "RQst", to: "46", title: "Score", color: "#d0cae1"},
{from: "panoptic-segmentation-on-coco-minival", to: "AP", title: "Metric", color: "#9c8acb"},
{from: "AP", to: "33", title: "Score", color: "#d0cae1"},
{from: "facebook/detr-resnet-101", to: "object-detection-on-coco-minival", title: "Benchmark", color: "#c1e769"},
{from: "object-detection-on-coco-minival", to: "box AP", title: "Metric", color: "#9c8acb"},
{from: "box AP", to: "44.9", title: "Score", color: "#d0cae1"},
{from: "object-detection-on-coco-minival", to: "AP50", title: "Metric", color: "#9c8acb"},
{from: "AP50", to: "64.7", title: "Score", color: "#d0cae1"},
{from: "object-detection-on-coco-minival", to: "AP75", title: "Metric", color: "#9c8acb"},
{from: "AP75", to: "47.7", title: "Score", color: "#d0cae1"},
{from: "object-detection-on-coco-minival", to: "APS", title: "Metric", color: "#9c8acb"},
{from: "APS", to: "23.7", title: "Score", color: "#d0cae1"},
{from: "object-detection-on-coco-minival", to: "APM", title: "Metric", color: "#9c8acb"},
{from: "APM", to: "49.5", title: "Score", color: "#d0cae1"},
{from: "object-detection-on-coco-minival", to: "APL", title: "Metric", color: "#9c8acb"},
{from: "APL", to: "62.3", title: "Score", color: "#d0cae1"},
{from: "facebook/detr-resnet-101", to: "object-detection-on-coco-o", title: "Benchmark", color: "#c1e769"},
{from: "object-detection-on-coco-o", to: "Average mAP", title: "Metric", color: "#9c8acb"},
{from: "Average mAP", to: "17.1", title: "Score", color: "#d0cae1"},
{from: "object-detection-on-coco-o", to: "Effective Robustness", title: "Metric", color: "#9c8acb"},
{from: "Effective Robustness", to: "-1.82", title: "Score", color: "#d0cae1"},
{from: "facebook/detr-resnet-101", to: "object_detection", title: "Python Code", color: "#348b40"},
{from: "google/vit-base-patch16-224", to: "google", title: "organisation", color: "#DE5947"},
{from: "google/vit-base-patch16-224", to: "image-classification", title: "Main Task", color: "#8EDE47"},
{from: "google/vit-base-patch16-224", to: "apache-2.0", title: "License", color: "#000000"},
{from: "google/vit-base-patch16-224", to: "dynamic-facial-expression-recognition-on-mafw", title: "Benchmark", color: "#c1e769"},
{from: "dynamic-facial-expression-recognition-on-mafw", to: "WAR", title: "Metric", color: "#9c8acb"},
{from: "WAR", to: "45.04", title: "Score", color: "#d0cae1"},
{from: "google/vit-base-patch16-224", to: "classify_image", title: "Python Code", color: "#348b40"},
{from: "microsoft/speecht5_tts", to: "microsoft", title: "organisation", color: "#DE5947"},
{from: "microsoft/speecht5_tts", to: "text-to-audio", title: "Main Task", color: "#8EDE47"},
{from: "microsoft/speecht5_tts", to: "mit", title: "License", color: "#000000"},
{from: "microsoft/speecht5_tts", to: "generate_speech", title: "Python Code", color: "#348b40"},
{from: "mistralai/Mistral-7B-Instruct-v0.1", to: "mistralai", title: "organisation", color: "#DE5947"},
{from: "mistralai/Mistral-7B-Instruct-v0.1", to: "text-generation", title: "Main Task", color: "#8EDE47"},
{from: "mistralai/Mistral-7B-Instruct-v0.1", to: "apache-2.0", title: "License", color: "#000000"},
{from: "mistralai/Mistral-7B-v0.1", to: "mistralai", title: "organisation", color: "#DE5947"},
{from: "mistralai/Mistral-7B-v0.1", to: "text-generation", title: "Main Task", color: "#8EDE47"},
{from: "mistralai/Mistral-7B-v0.1", to: "apache-2.0", title: "License", color: "#000000"},
{from: "mistralai/Mistral-7B-v0.1", to: "common-sense-reasoning-on-arc-challenge", title: "Benchmark", color: "#c1e769"},
{from: "common-sense-reasoning-on-arc-challenge", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "55.5", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "common-sense-reasoning-on-arc-easy", title: "Benchmark", color: "#c1e769"},
{from: "common-sense-reasoning-on-arc-easy", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "80.0", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "arithmetic-reasoning-on-gsm8k", title: "Benchmark", color: "#c1e769"},
{from: "arithmetic-reasoning-on-gsm8k", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "52.2", title: "Score", color: "#d0cae1"},
{from: "arithmetic-reasoning-on-gsm8k", to: "Parameters (Billion)", title: "Metric", color: "#9c8acb"},
{from: "Parameters (Billion)", to: "7", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "sentence-completion-on-hellaswag", title: "Benchmark", color: "#c1e769"},
{from: "sentence-completion-on-hellaswag", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "81.3", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "code-generation-on-humaneval", title: "Benchmark", color: "#c1e769"},
{from: "code-generation-on-humaneval", to: "Pass@1", title: "Metric", color: "#9c8acb"},
{from: "Pass@1", to: "30.5", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "zero-shot-video-question-answer-on-intentqa", title: "Benchmark", color: "#c1e769"},
{from: "zero-shot-video-question-answer-on-intentqa", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "50.4", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "math-word-problem-solving-on-math", title: "Benchmark", color: "#c1e769"},
{from: "math-word-problem-solving-on-math", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "13.1", title: "Score", color: "#d0cae1"},
{from: "math-word-problem-solving-on-math", to: "Parameters (Billions)", title: "Metric", color: "#9c8acb"},
{from: "Parameters (Billions)", to: "7", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "code-generation-on-mbpp", title: "Benchmark", color: "#c1e769"},
{from: "code-generation-on-mbpp", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "47.5", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "multi-task-language-understanding-on-mmlu", title: "Benchmark", color: "#c1e769"},
{from: "multi-task-language-understanding-on-mmlu", to: "Average (%)", title: "Metric", color: "#9c8acb"},
{from: "Average (%)", to: "60.1", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "question-answering-on-natural-questions", title: "Benchmark", color: "#c1e769"},
{from: "question-answering-on-natural-questions", to: "EM", title: "Metric", color: "#9c8acb"},
{from: "EM", to: "28.8", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "zero-shot-video-question-answer-on-next-gqa", title: "Benchmark", color: "#c1e769"},
{from: "zero-shot-video-question-answer-on-next-gqa", to: "Acc@GQA", title: "Metric", color: "#9c8acb"},
{from: "Acc@GQA", to: "9.2", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "zero-shot-video-question-answer-on-next-qa", title: "Benchmark", color: "#c1e769"},
{from: "zero-shot-video-question-answer-on-next-qa", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "51.1", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "question-answering-on-piqa", title: "Benchmark", color: "#c1e769"},
{from: "question-answering-on-piqa", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "83.0", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "question-answering-on-triviaqa", title: "Benchmark", color: "#c1e769"},
{from: "question-answering-on-triviaqa", to: "EM", title: "Metric", color: "#9c8acb"},
{from: "EM", to: "69.9", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "common-sense-reasoning-on-winogrande", title: "Benchmark", color: "#c1e769"},
{from: "common-sense-reasoning-on-winogrande", to: "Accuracy", title: "Metric", color: "#9c8acb"},
{from: "Accuracy", to: "75.3", title: "Score", color: "#d0cae1"},
{from: "mistralai/Mistral-7B-v0.1", to: "en", title: "language", color: "#9ac7e3"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "nvidia", title: "organisation", color: "#DE5947"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "image-segmentation", title: "Main Task", color: "#8EDE47"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "other", title: "License", color: "#000000"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "semantic-segmentation-on-deliver-1", title: "Benchmark", color: "#c1e769"},
{from: "semantic-segmentation-on-deliver-1", to: "mIoU", title: "Metric", color: "#9c8acb"},
{from: "mIoU", to: "57.20", title: "Score", color: "#d0cae1"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "thermal-image-segmentation-on-rgb-t-glass", title: "Benchmark", color: "#c1e769"},
{from: "thermal-image-segmentation-on-rgb-t-glass", to: "MAE", title: "Metric", color: "#9c8acb"},
{from: "MAE", to: "0.053", title: "Score", color: "#d0cae1"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "semantic-segmentation-on-selma", title: "Benchmark", color: "#c1e769"},
{from: "semantic-segmentation-on-selma", to: "mIoU", title: "Metric", color: "#9c8acb"},
{from: "mIoU", to: "77.2", title: "Score", color: "#d0cae1"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "semantic-segmentation-on-urbanlf", title: "Benchmark", color: "#c1e769"},
{from: "semantic-segmentation-on-urbanlf", to: "mIoU (Real)", title: "Metric", color: "#9c8acb"},
{from: "mIoU (Real)", to: "82.20", title: "Score", color: "#d0cae1"},
{from: "semantic-segmentation-on-urbanlf", to: "mIoU (Syn)", title: "Metric", color: "#9c8acb"},
{from: "mIoU (Syn)", to: "78.53", title: "Score", color: "#d0cae1"},
{from: "nvidia/segformer-b0-finetuned-ade-512-512", to: "classify_image", title: "Python Code", color: "#348b40"},
{from: "openai/whisper-large-v2", to: "openai", title: "organisation", color: "#DE5947"},
{from: "openai/whisper-large-v2", to: "automatic-speech-recognition", title: "Main Task", color: "#8EDE47"},
{from: "openai/whisper-large-v2", to: "apache-2.0", title: "License", color: "#000000"},
{from: "openai/whisper-large-v2", to: "speech-recognition-on-common-voice-english", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-common-voice-english", to: "Word Error Rate (WER)", title: "Metric", color: "#9c8acb"},
{from: "Word Error Rate (WER)", to: "9.4%", title: "Score", color: "#d0cae1"},
{from: "openai/whisper-large-v2", to: "speech-recognition-on-common-voice-french", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-common-voice-french", to: "Test WER", title: "Metric", color: "#9c8acb"},
{from: "Test WER", to: "13.9%", title: "Score", color: "#d0cae1"},
{from: "openai/whisper-large-v2", to: "speech-recognition-on-common-voice-german", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-common-voice-german", to: "Test WER", title: "Metric", color: "#9c8acb"},
{from: "Test WER", to: "6.4%", title: "Score", color: "#d0cae1"},
{from: "openai/whisper-large-v2", to: "speech-recognition-on-common-voice-italian", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-common-voice-italian", to: "Test WER", title: "Metric", color: "#9c8acb"},
{from: "Test WER", to: "7.1%", title: "Score", color: "#d0cae1"},
{from: "openai/whisper-large-v2", to: "speech-recognition-on-common-voice-spanish", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-common-voice-spanish", to: "Test WER", title: "Metric", color: "#9c8acb"},
{from: "Test WER", to: "5.6%", title: "Score", color: "#d0cae1"},
{from: "openai/whisper-large-v2", to: "automatic_speech_recognition", title: "Python Code", color: "#348b40"},
{from: "openai/whisper-large-v2", to: "en", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "zh", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "de", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "es", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ru", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ko", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "fr", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ja", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "pt", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "tr", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "pl", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ca", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "nl", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ar", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sv", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "it", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "id", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "hi", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "fi", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "vi", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "he", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "uk", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "el", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ms", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "cs", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ro", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "da", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "hu", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ta", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "th", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ur", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "hr", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "bg", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "lt", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "la", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "mi", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ml", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "cy", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sk", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "te", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "fa", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "lv", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "bn", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sr", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "az", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sl", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "kn", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "et", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "mk", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "br", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "eu", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "is", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "hy", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ne", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "mn", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "bs", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "kk", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sq", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sw", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "gl", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "mr", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "pa", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "si", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "km", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sn", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "yo", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "so", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "af", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "oc", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ka", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "be", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "tg", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sd", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "gu", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "am", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "yi", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "lo", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "uz", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "fo", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ht", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ps", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "tk", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "nn", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "mt", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "sa", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "lb", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "my", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "bo", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "tl", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "mg", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "as", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "tt", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "haw", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ln", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ha", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "ba", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "jw", title: "language", color: "#9ac7e3"},
{from: "openai/whisper-large-v2", to: "su", title: "language", color: "#9ac7e3"},
{from: "stabilityai/stable-diffusion-2-1", to: "stabilityai", title: "organisation", color: "#DE5947"},
{from: "stabilityai/stable-diffusion-2-1", to: "text-to-image", title: "Main Task", color: "#8EDE47"},
{from: "stabilityai/stable-diffusion-2-1", to: "openrail++", title: "License", color: "#000000"},
{from: "deepseek-ai/deepseek-coder-6.7b-instruct", to: "deepseek-ai", title: "organisation", color: "#DE5947"},
{from: "deepseek-ai/deepseek-coder-6.7b-instruct", to: "text-generation", title: "Main Task", color: "#8EDE47"},
{from: "deepseek-ai/deepseek-coder-6.7b-instruct", to: "other", title: "License", color: "#000000"},
{from: "deepseek-ai/deepseek-coder-6.7b-instruct", to: "generate_response", title: "Python Code", color: "#348b40"},
{from: "stabilityai/stable-diffusion-xl-base-1.0", to: "stabilityai", title: "organisation", color: "#DE5947"},
{from: "stabilityai/stable-diffusion-xl-base-1.0", to: "text-to-image", title: "Main Task", color: "#8EDE47"},
{from: "stabilityai/stable-diffusion-xl-base-1.0", to: "openrail++", title: "License", color: "#000000"},
{from: "stabilityai/stable-diffusion-xl-base-1.0", to: "run_model", title: "Python Code", color: "#348b40"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "nvidia", title: "organisation", color: "#DE5947"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "automatic-speech-recognition", title: "Main Task", color: "#8EDE47"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "cc-by-4.0", title: "License", color: "#000000"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "speech-recognition-on-common-voice-english", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-common-voice-english", to: "Word Error Rate (WER)", title: "Metric", color: "#9c8acb"},
{from: "Word Error Rate (WER)", to: "5.8%", title: "Score", color: "#d0cae1"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "speech-recognition-on-librispeech-test-clean", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-librispeech-test-clean", to: "Word Error Rate (WER)", title: "Metric", color: "#9c8acb"},
{from: "Word Error Rate (WER)", to: "1.46", title: "Score", color: "#d0cae1"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "speech-recognition-on-librispeech-test-other", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-librispeech-test-other", to: "Word Error Rate (WER)", title: "Metric", color: "#9c8acb"},
{from: "Word Error Rate (WER)", to: "2.48", title: "Score", color: "#d0cae1"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "speech-recognition-on-spgispeech", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-spgispeech", to: "Word Error Rate (WER)", title: "Metric", color: "#9c8acb"},
{from: "Word Error Rate (WER)", to: "3.11", title: "Score", color: "#d0cae1"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "speech-recognition-on-tedlium", title: "Benchmark", color: "#c1e769"},
{from: "speech-recognition-on-tedlium", to: "Word Error Rate (WER)", title: "Metric", color: "#9c8acb"},
{from: "Word Error Rate (WER)", to: "3.92", title: "Score", color: "#d0cae1"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "automatic_speech_recognition", title: "Python Code", color: "#348b40"},
{from: "nvidia/parakeet-rnnt-1.1b", to: "en", title: "language", color: "#9ac7e3"},
];
